### ISSUE TITLE
Add "Import/Export Labels" .csv function

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/Tokenly-Pockets#11]
Anybody managing more than one wallet needs this, which might not be everybody buts its power users and basically pockets become counterproductive when you lose names each time you change wallets

I imagine its just a .csv that associates 
{bitcoin address}, {label name}
{bitcoin address}, {label name}
{bitcoin address}, {label name}
{bitcoin address}, {label name}

When imported the wallet would check the addresses associated with the open wallet against the .csv and applies the labels to the appropriate addresses

When a .csv has more than the default five addresses worth of labels, the wallet should add those additional addresses and apply the labels appropriately.  Ideally a user would not have to click "add address" a bunch of times before importing the file.

**Comment by loon3** [comment]
The first feature funded by POCKETCHANGE!  

Started working on this last night, export works fine (although it does involve an additional permission) but import has proven to be a bit tricky...

**Comment by loon3** [comment]
What if we eliminate the need to import/export and just have the extension archive all address/label pairs.

**Comment by AdamBLevine** [comment]
Do you mean that the extension locally installed would archive or do you mean that we'd have a server or three collecting and serving this information when a wallet checks if any of those addresses have labels

The first option has the problem of not working across multiple computers or re-installations while the latter option has privacy implications that are problematic.  It would be trivial for us to associate addresses and their labels with user IP addresses, so labels would need to be basically encrypted by the private key that controls the related public key.   I like the second approach better than the first because the first does not really solve the problem and the second would be very easy for users, not involving keeping any files at all

**Comment by loon3** [comment]
Ok, so it's not just for entering different passphrases within the same wallet.  I'll stick with the original idea of importing/exporting for now, I think that will be cleanest and most versatile.

**Comment by AdamBLevine** [comment]
No it's both different passphrases in the same wallet, recovering wallets when you've had to reinstall the extension and recover your wallet for some reason or using multiple computers with the same wallet (just email or dropbox the label file)

**Comment by loon3** [comment]
https://github.com/loon3/Tokenly-Pockets/commit/a788efffc0ae66b4fea5aea3e81a03d3263dde34

using .json file instead of .csv
