### ISSUE TITLE
Major Bug - "Insufficient funds" error in new version

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/Tokenly-Pockets#13]
![image](https://cloud.githubusercontent.com/assets/6858319/9700217/0981d3d4-53b0-11e5-877b-8be94a900d00.png)

I've confirmed this is happening for at least three users, blockchain shows the funds are there, counterwallet processes the transactions properly but Pockets says "insufficient funds" and fails

**Comment by loon3** [comment]
fixed https://github.com/loon3/Tokenly-Pockets/commit/36321b497c7cbe6e0abbcbcdb136aaa54a0f8e8a
