### ISSUE TITLE
Transaction not displaying in wallet

### ISSUE THREAD

**Issue by pairmike** [loon3/Tokenly-Pockets#19]
Devon, 

Yesterday I sent some BTC to my Tokenly Pockets wallet and the transaction is not showing up.  Here are the details.  https://blockchain.info/tx/50fedb4341e324527d01e6bb4913d8ac83321a18d04eccd06ebb04472542fe1c

**Comment by loon3** [comment]
Is your total BTC balance correct?  I fixed a bug causing certain BTC txs not to appear but it hasn't been pushed to the Chrome Web Store in an update yet.

**Comment by pairmike** [comment]
No, my BTC balance in Pockets is not correct.

**Comment by pairmike** [comment]
https://coinplorer.com/BTC/Addresses/1KEUhnzMCQdn1PmU1sG3qPfCpPFt9vRHqq  The balance here is showing the correct total BTC, but it is not reflected in the Tokenly wallet.

**Comment by loon3** [comment]
Found the issue.

Pockets uses Blockr which appears to be stuck at block 377950, http://btc.blockr.io/, so the balance in Pockets will reflect whatever your balance was at block 377950.  This also explains why your transaction isn't appearing since it was included in block 377951.

I sent a message to @blockr_io on twitter and will keep this issue open until it's back up to date.

**Comment by pairmike** [comment]
Thanks Joe.  That makes sense now.

Thanks,

Michael Pair
Shop Online and Earn Money http://mss.me/mpair
New to Bitcoin. Listen to Let's Talk Bitcoin
http://letstalkbitcoin.com?ref=365cab70
Donate Bitcoins http://www.coinbase.com/mikepair
Earn Free Bitcoins
http://earnfreebitcoins.com?ref=1Pa8fckbcdiMAA4twWyvdgbQ7QYoQMiBct

**Comment by loon3** [comment]
Looks like blockr.io is caught up now, take a look and let me know if it's showing you the correct balance

**Comment by pairmike** [comment]
Joe,

The BTC amount in the wallet has been updated.  Thanks for your help.

Mike

Thanks,

Michael Pair
Shop Online and Earn Money http://mss.me/mpair
New to Bitcoin. Listen to Let's Talk Bitcoin
http://letstalkbitcoin.com?ref=365cab70
Donate Bitcoins http://www.coinbase.com/mikepair
Earn Free Bitcoins
http://earnfreebitcoins.com?ref=1Pa8fckbcdiMAA4twWyvdgbQ7QYoQMiBct

**Comment by loon3** [comment]
Great!
