### ISSUE TITLE
Unable to send

### ISSUE THREAD

**Issue by darkdesire71** [loon3/Tokenly-Pockets#27]
I have been trying to send coins for several hours, and i keep getting the message "Something is wrong, please try again later Transaction Failed!" I have sufficient BTC to send the coins (0.0008543) and the address is 100% correct, Any idea why it's failing please ?

**Comment by darkdesire71** [comment]
Even imported the pocket to Iron browser and still the same, wont send from my address

**Comment by BlackTowerFLDC** [comment]
I have sufficient BTC 0.0001629 for 1 transaction as well and I am unable to send FLDC. I don't get any message though, it just says sending and it eventually locks me out, if I keep it active it goes on sending forever.

**Comment by loon3** [comment]
It may be an issue with the API used to broadcast transactions.  Try using your passphrase at freewallet.io
