### ISSUE TITLE
Integrate Glidera API to allow in-wallet BTC on/off ramp

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/Tokenly-Pockets#3]
Glidera offers an API that lets us allow users buy or sell BTC within the wallet in a legally compliant fashion - This is desirable because right now our assumed onramp is "register with Circle, Coinbase or use LocalBitcoins.com to buy BTC and then send it to the wallet" which is not simple.

https://www.glidera.com/developers

**Comment by loon3** [comment]
Interesting, so it's like Coinbase without a wallet?  Would be nice if they had an example workflow on the website.

**Comment by AdamBLevine** [comment]
See this?

https://www.glidera.com/documentation#exampleCode

Not a workflow but they do have documentation and example code

**Comment by loon3** [comment]
Yeah, but it doesn't include making an account at Glidera, entering bank account info, etc.

**Comment by loon3** [comment]
well, it does show that if you flip through all the api docs but it would be nice to have an actual example of how it would look to the user

**Comment by loon3** [comment]
integrated in v0.2.0
