### ISSUE TITLE
Asset decoding is slightly off for some names

### ISSUE THREAD

**Issue by deweller** [loon3/Tokenly-Pockets#5]
For this transaction:

https://counterpartychain.io/transaction/88e9a4afc605a895f048c08d67f66f119311cc8d7af95562f2ed46b1e6c1559e

The asset should be ETHEREUMCARD.

But Tokenly Pockets parses the name as ETHEREUMCARC.

https://chain.so/tx/BTC/88e9a4afc605a895f048c08d67f66f119311cc8d7af95562f2ed46b1e6c1559e

![bitcoin_transaction__88e9a4afc605a895f048c08d67f66f119311cc8d7af95562f2ed46b1e6c1559e](https://cloud.githubusercontent.com/assets/51414/9052411/c6c626ae-3a2c-11e5-824a-2a3e96757723.png)

**Comment by loon3** [comment]
fixed in v0.1.7
