### ISSUE TITLE
When passphrase is entered during setup or at user demand, allow paranoid users to hide the text entry

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/Tokenly-Pockets#6]
Originally this was privacy protected but after user feedback the text was no longer hidden.  Now we've gotten feedback that some people are uncomfortable with the unhidden 12 word passphrase entry so I think the answer is to make it toggle-able based on user preference.   By default the password might be hidden but the checkbox can be unchecked and the text is not hidden.

**Comment by loon3** [comment]
Hide/Show button added

https://github.com/loon3/Tokenly-Pockets/commit/ef8c087fc4968edca52b571469f0d5f201cf6a58
